logging:
  level:
    tech:
      jhipster:
        lite:
          sample: DEBUG
management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: '*'
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
