logging:
  level:
    tech:
      jhipster:
        lite:
          sample: INFO
spring:
  application:
    name: Litesample
  jackson:
    default-property-inclusion: non_absent
  task:
    execution:
      pool:
        keep-alive: 10s
        max-size: 16
        queue-capacity: 100
      thread-name-prefix: litesample-task-
    scheduling:
      pool:
        size: 2
      thread-name-prefix: litesample-scheduling-
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/litesample
    username: litesample
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        jdbc:
          batch_size: 25
          time_zone: UTC
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid,profile,email
server:
  port: 8080
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
  info:
    env:
      enabled: true
    # Git Information
    git:
      enabled: true
      mode: full
application:
  security:
    oauth2:
      audience: account,api://default
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
    oauth:
      client-id: web_app
      realm: jhipster
  oauth2:
    authorization-url: http://localhost:9080/realms/jhipster/protocol/openid-connect/auth
