spring:
  application:
    name: Litesample
  threads:
    virtual:
      enabled: true
  task:
    scheduling:
      thread-name-prefix: litesample-scheduling-
      pool:
        size: 2
    execution:
      pool:
        keep-alive: 10s
        queue-capacity: 100
        max-size: 16
      thread-name-prefix: litesample-task-
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    password: ''
    driver-class-name: org.postgresql.Driver
    username: litesample
    url: jdbc:postgresql://localhost:5432/litesample
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-secret: web_app
            client-id: web_app
            scope: openid,profile,email
        provider:
          oidc:
            issuer-uri: http://localhost:9080/realms/jhipster
logging:
  level:
    tech:
      jhipster:
        lite:
          sample: INFO
server:
  port: 8080
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - threaddump
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  info:
    # Git Information
    git:
      mode: full
      enabled: true
    env:
      enabled: true
application:
  security:
    oauth2:
      audience: account,api://default
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
    oauth:
      client-id: web_app
      realm: jhipster
  enable-native-support: true
  oauth2:
    authorization-url: http://localhost:9080/realms/jhipster/protocol/openid-connect/auth
