# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    command: 'start-dev --import-realm'
    volumes:
      - ./keycloak-realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - '127.0.0.1:9080:9080'
      - '127.0.0.1:9443:9443'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '[ -f /tmp/JHipsterKeycloakHealthCheck.java ] || echo "public class JHipsterKeycloakHealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/JHipsterKeycloakHealthCheck.java && java /tmp/JHipsterKeycloakHealthCheck.java http://localhost:9000/health/live',
        ]
      interval: 5s
      timeout: 5s
      retries: 30
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true
