name: GitHub Actions
on: [push]
jobs:
  #--------------------------------------------------
  # Build and Tests the project on Linux
  #--------------------------------------------------
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:{{ =<% %>= }}
      - name: 'Setup: checkout project'
        uses: actions/checkout@v2
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: 'Init: cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-<%={{  }}=%>
      - name: 'Test: run tests'
        run: |
          chmod +x mvnw
          ./mvnw clean verify
